# Generated by Django 4.1.5 on 2023-01-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rianablog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
